### ISSUE TITLE
upgrade FV server to V9

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#277] opened 2020-10-21 06:58 UTC
- [x] install v9 *standard* server on fvqa - version 9.0.4 (currently we use custom)
- [x] add mongodb docker to our -withproxy.yml - give it a docker hostname facetec-mongodb
- [x] setup v9 config file to connect to mongodb plus license info
- [x] build script to migrate v8 data to v9 see https://dev.facetec.com/api-guide#import-3d-facemap
   - read facemap from v8 (maybe possible to just read the facemap file)
   - call import-3d-facemap
   - make sure to use same faceid

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-22 15:44
@sirpy I've configured everything. MongoDB instance was added, ZoOm server will be accessible under localhost:8081. Server is starting, successfully connects to  mongo and have access to the search DB directory. But i've encountered with the keys validation issue:

```
com.facetec.servercore.FaceTecInitException: The Device/Server keys failed validation.
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.nativeInitializeInDevelopmentMode(Native Method)
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.initializeInDevelopmentMode(FaceTecSDK.java:71)
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.initializeInDevelopmentMode(FaceTecSDK.java:52)
facetec-server-standard_1  | 	at com.facetec.standardserver.classes.FaceTecInstanceManager.initialize(FaceTecInstanceManager.java:21)
facetec-server-standard_1  | 	at com.facetec.standardserver.classes.FaceTecServerState.initDatabaseConnectionAndFaceTecServerSDK(FaceTecServerState.java:48)
facetec-server-standard_1  | 	at com.facetec.standardserver.app.App.main(App.java:21)
facetec-server-standard_1  | FSS ERROR: Initialization was unsuccessful, please check the exception, your Keys and try again.  If the problem persists, please contact support@facetec.com for assistance.
facetec-server-standard_1  | FSS ERROR: The Device/Server keys failed validation.
facetec-server-standard_1  | FSS ERROR: An issue was encountered while initializing the FaceTec Server SDK, inspect the logs for more details.
facetec-server-standard_1  | FSS Info:  An issue was encountered while initializing the FaceTec Server SDK, inspect the logs for more details.
```

The logs are empty. Probably the issue is that we're using a production key running in development mode. Please, give me accesses to the ZoOm dashboard or provide keys values from https://dev.facetec.com/#/account

```
# Your Device Key Identifier can be found at https://dev.facetec.com/#/account
deviceKeyIdentifier: 

# Your Server Key can be found at https://dev.facetec.com/#/account
serverKey: 
```

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-23 12:16
@sirpy i found the server key identifier (64-char string starts with "Ml...") in the bash history. it's also required for v8 and you specifying it while building it's image some time ago (that way i found it),

Now v9 is working:
```
------------------------
facetec-server-standard_1  | FaceTec Server SDK is started and ready to go!
facetec-server-standard_1  | ------------------------

root@facetec-qa:~# curl http://localhost:8081/status
{"running":true,"success":true,"callData":{"tid":"63cf19be-b769-4bee-90e2-527f5f25e458","path":"/status","date":"Oct 23, 2020 12:11:23 PM","epochSecond":1603455083,"requestMethod":"GET"},"additionalSessionData":{"isAdditionalDataPartiallyIncomplete":true},"error":false,"serverInfo":{"version":"9.0.4","type":"Standard","mode":"Development Only","notice":"You should only be reading this if you are in server-side code.  Please make sure you do not allow the FaceTec Server to be called from the public internet."}}
```

I'll add systemd startup scripts for v8 (as it's down again) and v9 then will switch to the migrate task

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-23 17:10
@sirpy 

I wrote a simple nodejs app for migration in /facetech/migrate.

For now i met with the following issue during the import:

```
Decryption was not possible for one of the encrypted function inputs (FaceScan, FaceMap, or IDScan).  This typically indicates that the encrypted data you are trying to use was created using Keys that your Server SDK is not configured to use.  Please double check all of your Keys and try again.  For more information about Device, Server, and FaceMap Encryption Keys, please see the Developer Documentation.
```

Not sure why it's happening because i used the same encryption key for import like was on goodqa. Will continue solving that issue at Monday

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-23 17:13
@sirpy 

To manage zoom instances on fvqa:

v8: `systemctl start|stop|restart facetec`
v9: `systemctl start|stop|restart facetec9`

running both issues could cause performance issues so i stopped v9 for now, launched it only during migration attempts

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-26 13:34
The script was finished. I continue getting issues with keys.

Firstly:
- i've took the exact _public_ key from the goodqa.netlify.app env
- i've took the exact _private_ key from `keys/PrivateKeyForFaceMapEncryption.pem` (it's using for build v8 image, so v8 serve uses it)

Then i got the error 'The encryption key was missing or invalid'. 

I supposed v8 keys aren't compatible with v9 and started reading the docs. On that page https://dev.facetec.com/facemap-encryption-keys i found that keys are generating via openssl utility. So v8 key should work with v9 as they both are just openssl keys. Invalid key message was because i specified PK in the wrong format (with \n for newlines). I've kept \n format for public keys only and reformatted the private key according the docs.

Now i'm getting the following error:

```
FSS ERROR: Initialization was unsuccessful, please check the exception, your Keys and try again.  If the problem persists, please contact support@facetec.com for assistance.
facetec-server-standard_1  | FSS ERROR: An unknown and unexpected error occurred.
facetec-server-standard_1  | FSS ERROR: An issue was encountered while initializing the FaceTec Server SDK, inspect the logs for more details.
facetec-server-standard_1  | FSS Info:  An issue was encountered while initializing the FaceTec Server SDK, inspect the logs for more details.
facetec-server-standard_1  | com.facetec.servercore.FaceTecInitException: An unknown and unexpected error occurred.
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.nativeInitializeInDevelopmentMode(Native Method)
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.initializeInDevelopmentMode(FaceTecSDK.java:71)
facetec-server-standard_1  | 	at com.facetec.servercore.FaceTecSDK.initializeInDevelopmentMode(FaceTecSDK.java:52)
facetec-server-standard_1  | 	at com.facetec.standardserver.classes.FaceTecInstanceManager.initialize(FaceTecInstanceManager.java:21)
facetec-server-standard_1  | 	at com.facetec.standardserver.classes.FaceTecServerState.initDatabaseConnectionAndFaceTecServerSDK(FaceTecServerState.java:48)
```

The logs are empty. Probably the issue appears because of hardware resources insufficiency (server has 4Gb RAM only).
I'll try to run it from the Docker locally. It the issue in something else, we have to contact ZoOm to resolve that issue

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-26 15:38
@sirpy Server runs locally (3.1 GHz i5 SkyLake + 8Gb RAM) without any issues.  So most probably the reason of 'unknown and unexpected error' is the lack of RAM

Anyway, the migration fails with the same 'invalid key' error:

```
Error migrating faceID 'a31090d63d306089bbe1165b45e578c3487c409a': Decryption was not possible for one of the encrypted function inputs (FaceScan, FaceMap, or IDScan).  This typically indicates that the encrypted data you are trying to use was created using Keys that your Server SDK is not configured to use.  Please double check all of your Keys and try again.  For more information about Device, Server, and FaceMap Encryption Keys, please see the Developer Documentation.
```

It's despite i used now the exactly same keys which were used on v8 fvqa (private key from fvqa /facetech/keys and public key from goodqa netlify env)

**Comment by serdiukov-o-nordwhale** [comment] 2020-10-26 15:51
what if the format of the facemaps (non-encrypted) themselves are different between v8 and v9 ? in that case zoom decrypts the base64 string then checks for some markers in the decrypted data, don’t find them and fails ? (one more fact to this theory is that v8 stores also audit trail image as the non-encrypted jpeg, but v9 stores only facemaps, so the trail images could be encrypted with the map in a single data block)

probably it’s impossible to migrate v8 to v9 at all ? or we could put that question to the facetech team ? 

I checked the old API - there’s no export feature in v8
in v9 export import points are used to exchange data between v9 instances. according the docs, private key is used to decrypt face maps stored in DB or facemaps we importing, public key is used for export facemaps
i couldn't find any info regarding v8 to v9 data exchange

**Comment by sirpy** [comment] 2020-10-29 08:02
waiting for factec for migration script

**Comment by serdiukov-o-nordwhale** [comment] 2020-11-24 16:55
Re-configured Custom server:
- new 'custom-enrollment-3d-delete' made compatible with old API (now it's DELETE /enrollment-3d/:externalDatabaseRefID)
- refactored endpoint implementation (took theirs sample code but added handler to EnrollmentGetAndDeleteProcessor, updated EnrollmentHelpers to handle also DELETE request)
- added mongodb container
- updated config.yaml with keys & other options from our standard server

Pushed all modified Java sources here: https://github.com/GoodDollar/FaceTecSDK-custom-server/tree/master/FaceTecSDK-custom-server-9.0.8/src/main/java/com/facetec/customserver

**Comment by serdiukov-o-nordwhale** [comment] 2020-11-25 12:59
@sirpy 

Added v8 import endpoint.

I found that import code provided is almost the same that existing Import3DFaceMapProcessor. So i:

- created abstract class ImportProcessor implementing everything is common in the both import flows
- created Import3DFaceMapProcessor extending ImportProcessor which re-creates the face map (as it was in the existing Import3DFaceMapProcessor)
- created ImportV8FaceMapProcessor extending ImportProcessor which just validates facemap and imports it 'as is' (according to the implementation of CustomImport3DFaceMapProcessor FaceTec has sent today)
- attached ImportV8FaceMapProcessor to /import-v8-facemap context

All changes related to the custom v8 endpoints are here: https://github.com/GoodDollar/FaceTecSDK-custom-server/commit/2088e15112ef15bdec84a5d085e9318c68751280

**Comment by serdiukov-o-nordwhale** [comment] 2020-11-25 14:24
moved to backlog, the import endpoint is till doesn't working. error comes from the FaceTecSDK-server-core-java-9.0.8 which is pre-compiled

if to send files 'as is':
com.facetec.servercore.FaceTecException: This error is returned when one of the matching functions is called with invalid parameter. For instance, this exception will be thrown if a 3D FaceMap is passed in where a 3D FaceScan should be passed.
facetec_custom_server_1  | 	at com.facetec.servercore.FaceTecSDKInstance.nativeGetFaceMapAuditData(Native Method)
facetec_custom_server_1  | 	at com.facetec.servercore.FaceTecSDKInstance.getFaceMapAuditData(FaceTecSDKInstance.java:370)
facetec_custom_server_1  | 	at com.facetec.customserver.processors.ImportV8FaceMapProcessor.import3DFaceMap(ImportV8FaceMapProcessor.java:15)

if to send the .facemap files content in base64:
Decryption was not possible for one of the encrypted function inputs (FaceScan, FaceMap, or IDScan).  This typically indicates that the encrypted data you are trying to use was created using Keys that your Server SDK is not configured to use.  Please double check all of your Keys and try again.  For more information about Device, Server, and FaceMap Encryption Keys, please see the Developer Documentation.

i re - checked again - the creds are exactly the same like on the v8 fvqa
I propose to send facetec our QA maps as the examples and ask them how actually we have to process those files before POST to import endpoint

Also, probably we wouldn't import old database ? because we anyway will ask for re-verefication each 2 weeks so why we couldn't do that when our app with v9 Zoom support will be released ?

**Comment by serdiukov-o-nordwhale** [comment] 2020-12-03 11:12
removed `extra` prop from `/status` endpoint response as we're not using it anymore (now we're detecting the case server doesn't supports `DELETE /enrollment-3d` analyzing exception was thrown on that call)

**Closed** 2021-01-26 18:52 UTC
